steps:
# #First Clone from Google Cloud Source Repository  
# - name: 'gcr.io/cloud-builders/git'
#   args: ['clone','https://source.developers.google.com/p/${_PROJECT}/r/${_REPO_NAME}']

#Build the image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}','.']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']
  
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENTNAME}'
  - '${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
substitutions:
    _PROJECT: poc-dev-273008
    _ZONE: us-central1-c
    _GKE_CLUSTER: testing
    _DEPLOYMENTNAME: hello-world-service
    _CONTAINERNAME: hello-world-service-sha256-1    
    _REPO_NAME: github_prashantmaheshwari_cicd-service
    _VERSION: v2.0
    
options:
    substitution_option: 'ALLOW_LOOSE'

